# Style different theme settings
theme:
  # A path to a wallpaper to use.
  wallpaper:

# Disable the use of a compositor when set to true. Otherwise picom will be started.
disable_compositor:

# Configure dpi settings for the displays
dpi:
  # Overwrite the automatically detected DPI for an output.
  # Specify here key value pairs where the key is the output name
  # as shown by xrandr and the value a dpi to set.

screensaver:
  # Configure how many minutes before the screen will be locked (Default: 10)
  timeout: 10
  # A delay after locking the screen before putting the machine to suspend-then-hibernate
  suspend_delay: 10

calendar:
  # Specify a path to a .desktop file to execute when clicking the clock in the bar
  action:

# A YML list of keyboard layouts, that the user can switch through.
# The first one in this list will be used when starting awesome.
keyboard_layouts:
  - us
## Set this property to enable brightness control. You must make sure to have write permission
## to this file. See scripts/brightness.sh for more information.
# brightness_device: /sys/class/backlight/intel_backlight

keyboard:
  # The hardware layout of the buttons.
  # "regular" is a regular full sized keyboard with a separate menu from print key.
  # "assistant" is a keyboard with a dedicated assistant key (with menu as sub function) beside the space bar and no print key.
  # "print" is a keyboard with a print key beside the space bar
  key_layout: regular

# If a Elgato key light is connected specify the IP address to control it via the control center
# elgato_key_light_ip: <ip address>
